<?php
namespace Handling;

use Core\Router;
use Exception;

/**
 * Handling the case of urls which may be occurred
 */
class Routing extends Router {

    /**
     * Predicting and handling for the possible cases
     * @param $route
     * @param array $param
     * */
    public function routes($route, $param = []) {
        $this->addLastSlash($route, $param);
    }

    /**
     * Handling same route whether user enter the last slash or not
     * @param $route
     * @param array $param
     * */
    public function addLastSlash($route, $param = []) {
        $this->add(rtrim($route, '/ '), $param);
        $this->add(rtrim($route, '/ ').'/', $param);
    }

    /**
     * Extending the parent dispatch()
     * @param $url
     *
     * @throws Exception
     */
    public function dispatch($url)
    {
        parent::dispatch($url); // TODO: Change the autogenerated stub
    }
}