module.exports = {
  future: {
    // removeDeprecatedGapUtilities: true,
    // purgeLayersByDefault: true,
  },
  purge: [],
  theme: {
    extend: {
      lineHeight: {
        icon: '21px',
        '10px': '10px',
        '13px': '13px',
        '41px': '41px',
        '35px': '35px',
        '14px': '14px',
        '50px': '50px',
        '60px': '60px',
        '18px': '18px',
        '36px': '36px',
        '30px': '30px',
        '150px': '150px',
        '515px': '515px',
        advanceSearchHeightCalculated: 'calc( 100vh - 250px )',
      },
      height: {
        icon: '21px',
        '10px': '10px',
        '13px': '13px',
        '41px': '41px',
        '35px': '35px',
        '14px': '14px',
        '50px': '50px',
        '60px': '60px',
        '18px': '18px',
        '36px': '36px',
        '30px': '30px',
        '150px': '150px',
        '515px': '515px',
        '66vh': '66vh',
        advanceSearchHeightCalculated: 'calc( 100vh - 250px )',
      },
      maxHeight: {
        10: '2.5rem',
        '50px': '50px',
        '150px': '150px',
        '66vh': '66vh',
        4: '1rem',
      },
      minHeight: {
        10: '2.5rem',
        '34px': '34px',
        4: '1rem',
      },
      width: {
        icon: '21px',
        '10px': '10px',
        '13px': '13px',
        '14px': '14px',
        '60px': '60px',
        '180px': '180px',
        '18px': '18px',
        '36px': '36px',
        '30px': '30px',
        '50px': '50px',
        '150px': '150px',
        '320px': '320px',
        1000: '62.5rem',
        advanceSearchWidthMaximum: '624px',
      },
      maxWidth: {
        10: '2.5rem',
        advanceSearchWidthMaximum: '624px',
        '36px': '36px',
        40: '10rem',
        '50px': '50px',
        '150px': '150px',
        1000: '62.5rem',
        4: '1rem',
      },
      minWidth: {
        '36px': '36px',
        40: '10rem',
        4: '1rem',
        '250px': '250px',
      },
      textColor: {
        menuItem: '#54698d',
        labelAndTitle: '#16325c',
        buttonAndURL: '#2a9cff',
        placeholderStyle: '#a8b7c7',
        menuIcon: '#a8b7c7',
        cmsRed: '#ff4c7f',
        cmsGreen: '#35b93f',
        cmsOrange: '#ff6f00',
        cmsRedNotify: '#ffdfe8',
        Orange: '#ffa613',
        cmsGray: '#e0e5ee',
        cmsDarkGreen: '#00594f',
        cmsLightGreen: '#00bda6',
        cmsLightBlue: '#62b7ed',
        cmsLight: '#f3fcfb',
      },
      borderColor: {
        menuItem: '#54698d',
        menuIcon: '#a8b7c7',
        buttonAndURL: '#2a9cff',
        cmsRed: '#ff4c7f',
        cmsGreen: '#35b93f',
        cmsOrange: '#ff6f00',
        cmsOrangeNotify: '#fff0a2',
        cmsRedNotify: '#ffdfe8',
        Orange: '#ffa613',
        cmsGray: '#e0e5ee',
        cmsDarkGreen: '#00594f',
        cmsLightGreen: '#00bda6',
        cmsLightBlue: '#62b7ed',
        cmsLight: '#f3fcfb',
      },
      fill: {
        menuItem: '#54698d',
        menuIcon: '#a8b7c7',
        labelAndTitle: '#16325c',
        buttonAndURL: '#2a9cff',
        placeholderStyle: '#a8b7c7',
        cmsRed: '#ff4c7f',
        cmsGreen: '#35b93f',
        cmsOrange: '#ff6f00',
        cmsOrangeNotify: '#fff0a2',
        cmsRedNotify: '#ffdfe8',
        Orange: '#ffa613',
        cmsGray: '#e0e5ee',
        cmsDarkGreen: '#00594f',
        cmsLightGreen: '#00bda6',
        cmsLightBlue: '#62b7ed',
        cmsLight: '#f3fcfb',
      },
      stroke: {
        menuItem: '#54698d',
        menuIcon: '#a8b7c7',
        labelAndTitle: '#16325c',
        buttonAndURL: '#2a9cff',
        placeholderStyle: '#a8b7c7',
        cmsRed: '#ff4c7f',
        cmsGreen: '#35b93f',
        cmsOrange: '#ff6f00',
        cmsOrangeNotify: '#fff0a2',
        cmsRedNotify: '#ffdfe8',
        Orange: '#ffa613',
        cmsGray: '#e0e5ee',
        cmsDarkGreen: '#00594f',
        cmsLightGreen: '#00bda6',
        cmsLightBlue: '#62b7ed',
        cmsLight: '#f3fcfb',
      },
      fontFamily: {
        lato: ['Lato', 'sans-serif'],
      },
      fontSize: {
        '12px': '12px',
        '13px': '13px',
        '14px': '14px',
        '15px': '15px',
        '18px': '18px',
        8: '2rem',
        7: '1.75rem',
        6: '1.5rem',
      },
      screens: {
        sm: { max: '767px' },
      },
      inset: {
        16: '4rem',
        28: '7rem',
        100: '100%',
        50: '50%',
        '5px': '5px',
        '-5px': '-5px',
        '10px': '10px',
        '-10px': '-10px',
        '15px': '15px',
        '-15px': '-15px',
        '50px': '50px',
        '-50px': '-50px',
        2.5: '0.625rem',
        '-2.5': '-0.625rem',
      },
      translate: {
        50: '50%',
      },
      backgroundColor: {
        sidebarHover: '#f4f6f9',
        buttonAndURL: '#2a9cff',
        cmsRed: '#ff4c7f',
        cmsGreen: '#35b93f',
        cmsOrange: '#ff6f00',
        cmsGreenNotify: '#d0f8ce',
        cmsOrangeNotify: '#fff0a2',
        cmsRedNotify: '#ffdfe8',
        Orange: '#ffa613',
        menuItem: '#54698d',
        menuIcon: '#a8b7c7',
        cmsGray: '#e0e5ee',
        cmsDarkGreen: '#00594f',
        cmsLightGreen: '#00bda6',
        cmsLightBlue: '#62b7ed',
        cmsLight: '#f3fcfb',
      },
      placeholderColor: {
        menuItem: '#54698d',
        labelAndTitle: '#16325c',
        buttonAndURL: '#2a9cff',
        placeholderStyle: '#a8b7c7',
        menuIcon: '#a8b7c7',
        cmsRed: '#ff4c7f',
        cmsGreen: '#35b93f',
        cmsOrange: '#ff6f00',
        cmsRedNotify: '#ffdfe8',
        Orange: '#ffa613',
        cmsGray: '#e0e5ee',
        cmsDarkGreen: '#00594f',
        cmsLightGreen: '#00bda6',
        cmsLightBlue: '#62b7ed',
        cmsLight: '#f3fcfb',
      },
      boxShadow: {
        fixed: '0 0px 4px 2px rgba(0, 0, 0, 0.08)',
      },
      spacing: {
        52: '52px',
        '5px': '5px',
        '10px': '10px',
        '15px': '15px',
        '30px': '30px',
        '35px': '35px',
        '45px': '45px',
        '50px': '50px',
        '60px': '60px',
      },
      transitionProperty: {
        height: 'height',
        spacing: 'margin, padding',
      },
      backgroundOpacity: {
        5: '0.05',
        10: '0.1',
      },
      keyframes: {
      },
    },
    container: {
      center: true,
    },
    fill: (theme) => ({
      white: theme('colors.white'),
    }),
  },
  variants: {
    textColor: ['responsive', 'hover', 'focus', 'group-hover'],
    fill: ['responsive', 'hover', 'focus', 'group-hover'],
    backgroundColor: ['responsive', 'hover', 'focus', 'group-hover', 'checked'],
    inset: ['responsive', 'hover', 'focus', 'group-hover', 'checked'],
    display: ['responsive', 'hover', 'focus', 'group-hover', 'checked'],
    maxWidth: ['responsive'],
    whitespace: ['hover', 'focus'],
  },
  plugins: [
    function ({ addUtilities }) {
      const newUtilities = {
        '.filter-none': {
          filter: 'none',
        },
        '.filter-shadow': {
          filter: 'drop-shadow( 1px 1px 1px rgba(0, 0, 0, .3))',
        },
        '.filter-grayscale': {
          // filter: 'url("data:image/svg+xml;utf8,<svg xmlns=\'http://www.w3.org/2000/svg\'><filter id=\'grayscale\'><feColorMatrix type=\'matrix\' values=\'0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0\'/></filter></svg>#grayscale")',
          '-webkit-filter': 'grayscale(1)',
          '-moz-filter': 'grayscale(100%)',
          '-ms-filter': 'grayscale(100%)',
          '-o-filter': 'grayscale(100%)',
          filter: 'grayscale(100%)',
        },
        '.cms-typo': {
          fontFamily: 'Lato',
          fontWeight: 'normal',
        },
      };

      addUtilities(newUtilities, ['responsive', 'hover', 'focus', 'group-hover']);
    },
  ],
};
