version: '3.7'
services:
  redis:
    image: 'redis:latest'
    container_name: redis
    command:
      - redis-server
      - /etc/redis/redis.conf
      - '--appendonly'
      - 'yes'
    ports:
      - '${REDIS_CONNECTION_PORT}:6379'
    volumes:
      - './redis/data:/var/lib/redis'
      - './redis/etc:/etc/redis/'
    user: 1000:1000
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    volumes:
      - './rabbitmq/etc:/etc/rabbitmq'
      - './rabbitmq/data:/var/lib/rabbitmq'
    environment:
      RABBITMQ_ERLANG_COOKIE: '${RABBITMQ_ERLANG_COOKIE}'
      RABBITMQ_DEFAULT_USER: '${RABBITMQ_DEFAULT_USER}'
      RABBITMQ_DEFAULT_PASS: '${RABBITMQ_DEFAULT_PASS}'
      RABBITMQ_LOG_BASE: /var/log/rabbitmq
    ports:
      - '${RABBITMQ_CONNECTION_PORT}:5672'
      - '${RABBITMQ_CONNECTION_EXPORT}:15672'
    deploy:
      resources:
        limits:
          cpus: '0.5'
    user: 1000:1000
  mongo-setup:
    image: 'mongo:4.0.22'
    restart: on-failure
    networks:
      default:
    volumes:
    - ./mongodb/scripts:/scripts
    entrypoint: [ "/scripts/setup.sh" ] # Make sure this file exists (see below for the setup.sh)
    depends_on:
      - mongo
      - mongo1
      - mongo2
  mongo:
    image: 'mongo:4.0.22'
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--dbpath", "/var/lib/mongodb"]
    volumes:
      - './mongodb/etc/mongod.conf:/etc/mongod.conf'
      - './mongodb/data:/var/lib/mongodb'
  mongo1:
    image: 'mongo:4.0.22'
    expose:
      - 27017
    ports:
      - 27018:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--dbpath", "/var/lib/mongodb" ]
    volumes:
      - './mongodb/etc/mongod_rs0_1.conf:/etc/mongod.conf'
      - './mongodb/data_rs0_1:/var/lib/mongodb'
  mongo2:
    image: 'mongo:4.0.22'
    expose:
      - 27017
    ports:
      - 27019:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--dbpath", "/var/lib/mongodb" ]
    volumes:
      - './mongodb/etc/mongod_rs0_2.conf:/etc/mongod.conf'
      - './mongodb/data_rs0_2:/var/lib/mongodb'
