version: '3.7'
services:
  redis:
    image: 'redis:latest'
    container_name: redis
    command:
      - redis-server
      - /etc/redis/redis.conf
      - '--appendonly'
      - 'yes'
    ports:
      - '${REDIS_CONNECTION_PORT}:6379'
    volumes:
      - './redis/data:/var/lib/redis'
      - './redis/etc:/etc/redis/'
    user: '1000:1000'
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    volumes:
      - './rabbitmq/etc:/etc/rabbitmq'
      - './rabbitmq/data:/var/lib/rabbitmq'
    environment:
      RABBITMQ_ERLANG_COOKIE: '${RABBITMQ_ERLANG_COOKIE}'
      RABBITMQ_DEFAULT_USER: '${RABBITMQ_DEFAULT_USER}'
      RABBITMQ_DEFAULT_PASS: '${RABBITMQ_DEFAULT_PASS}'
      RABBITMQ_LOG_BASE: /var/log/rabbitmq
    ports:
      - '${RABBITMQ_CONNECTION_PORT}:5672'
      - '${RABBITMQ_CONNECTION_EXPORT}:15672'
    deploy:
      resources:
        limits:
          cpus: '0.5'
    user: '1000:1000'
  mongo-setup:
    image: 'mongo:4.0.22'
    networks:
      default: null
    volumes:
      - './mongodb/scripts:/scripts'
    entrypoint:
      - /scripts/setup.sh
    links:
      - mongo1
      - mongo2
      - mongo3
  mongo1:
    image: 'mongo:4.0.22'
    container_name: emz_mongo1
    ports:
      - '27017:27017'
    command: mongod --config /etc/mongod.conf
    volumes:
      - './mongodb/etc/mongod.conf:/etc/mongod.conf'
      - './mongodb/data_rs0_1:/var/lib/mongodb'
    user: '1000:1000'
    links:
      - mongo2
      - mongo3
  mongo2:
    image: 'mongo:4.0.22'
    container_name: emz_mongo2
    ports:
      - '27018:27017'
    command: mongod --config /etc/mongod.conf
    volumes:
      - './mongodb/etc/mongod.conf:/etc/mongod.conf'
      - './mongodb/data_rs0_2:/var/lib/mongodb'
    user: '1000:1000'
  mongo3:
    image: 'mongo:4.0.22'
    container_name: emz_mongo3
    ports:
      - '27019:27017'
    volumes:
      - './mongodb/etc/mongod.conf:/etc/mongod.conf'
      - './mongodb/data_rs0_3:/var/lib/mongodb'
    command: mongod --config /etc/mongod.conf
    user: '1000:1000'
