version: '3.7'

services:
  tenantfront:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8001:8001
    volumes: 
      - ./src:/app/src
    networks:
      - tada-network
    command: npm run start:dev
      
networks:
  tada-network:
    external: true